mongo-db:
    build: .
    dockerfile: db/Dockerfile
    ports:
        - "27017:27017"
    volumes: 
        - ./db/data:/db/data

items-server:
    build: .
    dockerfile: server/Dockerfile
    environment:
        - DB_ENV=production
    ports:
        - "4000:4000"
    links:
        - mongo-db
